# Generated by Django 4.1.3 on 2022-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurmHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_url', models.TextField(verbose_name='Entity_url')),
                ('application_name', models.TextField(verbose_name='Application name')),
                ('series', models.TextField(verbose_name='Series')),
                ('channel', models.TextField(verbose_name='Version ChurmHub package')),
                ('constraints', models.TextField(verbose_name='Machine named')),
                ('num_units', models.IntegerField(verbose_name='Count Machine')),
            ],
        ),
    ]
