# Generated by Django 4.1.3 on 2022-12-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churmhub',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
