# Generated by Django 4.1.3 on 2022-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0002_alter_churmhub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churmhub',
            name='application_name',
            field=models.CharField(max_length=400, verbose_name='Application name'),
        ),
        migrations.AlterField(
            model_name='churmhub',
            name='channel',
            field=models.CharField(max_length=400, verbose_name='Version ChurmHub package'),
        ),
        migrations.AlterField(
            model_name='churmhub',
            name='constraints',
            field=models.CharField(max_length=400, verbose_name='Machine named'),
        ),
        migrations.AlterField(
            model_name='churmhub',
            name='entity_url',
            field=models.CharField(max_length=400, verbose_name='Entity_url'),
        ),
        migrations.AlterField(
            model_name='churmhub',
            name='series',
            field=models.CharField(max_length=400, verbose_name='Series'),
        ),
    ]
