# Generated by Django 4.1.3 on 2023-01-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0003_alter_churmhub_application_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromJujuClientTerminal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id from juju clinet')),
                ('data_juju', models.TextField(verbose_name='Data[ip,cert,conf]')),
            ],
        ),
    ]
